### ISSUE TITLE
ADMIN PASSWORD SHOWS INCORRECT

### ISSUE THREAD

**Issue by yuvalshakti25** [md-ali-0/Dream-Craft-Events#172]
![Screenshot 2024-11-01 180729](https://github.com/user-attachments/assets/672568f5-080d-4b09-a462-2f938a32d354)
used the credentials given in readme.md as it is yet shows wrong password for admin@gmail.com

**Comment by md-ali-0** [comment]
Maybe Someone Changed the Password.
You can try again.
